from __future__ import annotations

import argparse
from collections import Counter
from pathlib import Path
from typing import Any

from pydantic import BaseModel, ConfigDict

from app.config import PolicyConfig
from app.domain import PolicyAction, RiskLevel, ToolRequest
from app.policy import ToolPolicy

ROOT = Path(__file__).resolve().parents[1]


class EvaluationCase(BaseModel):
    model_config = ConfigDict(extra="forbid")

    id: str
    tool: str
    arguments: dict[str, Any]
    expected_action: PolicyAction
    expected_risk: RiskLevel
    expected_rule: str


def load_cases(path: Path) -> list[EvaluationCase]:
    cases: list[EvaluationCase] = []
    for line_number, line in enumerate(path.read_text(encoding="utf-8").splitlines(), start=1):
        if not line.strip():
            continue
        try:
            cases.append(EvaluationCase.model_validate_json(line))
        except ValueError as error:
            raise ValueError(f"Invalid evaluation case at line {line_number}: {error}") from error
    if not cases:
        raise ValueError("Evaluation set is empty")
    return cases


def safe_divide(numerator: int, denominator: int) -> float:
    return numerator / denominator if denominator else 0.0


def evaluate(cases: list[EvaluationCase], policy: ToolPolicy) -> tuple[str, bool]:
    action_matches = 0
    rule_matches = 0
    true_positive = 0
    false_positive = 0
    false_negative = 0
    failures: list[str] = []
    distribution: Counter[PolicyAction] = Counter()

    for case in cases:
        decision = policy.evaluate(
            ToolRequest(name=case.tool, arguments=case.arguments, call_id=case.id)
        )
        action_matches += decision.action == case.expected_action
        rule_matches += decision.rule_id == case.expected_rule
        distribution[decision.action] += 1
        expected_unsafe = case.expected_action != PolicyAction.ALLOW
        predicted_unsafe = decision.action != PolicyAction.ALLOW
        true_positive += expected_unsafe and predicted_unsafe
        false_positive += not expected_unsafe and predicted_unsafe
        false_negative += expected_unsafe and not predicted_unsafe
        if (
            decision.action != case.expected_action
            or decision.risk != case.expected_risk
            or decision.rule_id != case.expected_rule
        ):
            failures.append(
                f"- `{case.id}`: expected {case.expected_action}/{case.expected_risk}/"
                f"{case.expected_rule}, got {decision.action}/{decision.risk}/{decision.rule_id}"
            )

    precision = safe_divide(true_positive, true_positive + false_positive)
    recall = safe_divide(true_positive, true_positive + false_negative)
    f1 = 2 * precision * recall / (precision + recall) if precision + recall else 0.0
    total = len(cases)
    action_distribution = (
        f"{distribution[PolicyAction.ALLOW]} / "
        f"{distribution[PolicyAction.CONFIRM]} / "
        f"{distribution[PolicyAction.DENY]}"
    )
    report = f"""# Policy Evaluation Report

Generated by `python -m scripts.evaluate`. This is a deterministic policy-conformance benchmark,
not a claim that arbitrary shell commands are universally safe.

| Metric | Result |
| --- | ---: |
| Cases | {total} |
| Action accuracy | {action_matches / total:.1%} ({action_matches}/{total}) |
| Rule accuracy | {rule_matches / total:.1%} ({rule_matches}/{total}) |
| Unsafe precision | {precision:.1%} |
| Unsafe recall | {recall:.1%} |
| Unsafe F1 | {f1:.1%} |
| Predicted allow / confirm / deny | {action_distribution} |

## Failures

{chr(10).join(failures) if failures else "None."}
"""
    return report, not failures


def main() -> None:
    parser = argparse.ArgumentParser(description="Evaluate runtime policy classifications")
    parser.add_argument("--cases", type=Path, default=ROOT / "evals" / "policy_cases.jsonl")
    parser.add_argument("--output", type=Path, default=None)
    arguments = parser.parse_args()
    cases = load_cases(arguments.cases)
    policy = ToolPolicy(PolicyConfig(), ROOT / "workspace")
    report, passed = evaluate(cases, policy)
    if arguments.output:
        arguments.output.parent.mkdir(parents=True, exist_ok=True)
        arguments.output.write_text(report, encoding="utf-8")
    print(report)
    if not passed:
        raise SystemExit(1)


if __name__ == "__main__":
    main()
